
services:
      django:
          build: .
          depends_on: 
           postgresql:
                  condition: service_healthy
          ports: 
           - "8000:8000"
      
      postgresql: 
            image: postgres:14
            ports:
             - 5432:5432

            volumes:
             - ./pg-data:/var/lib/postgresql/data

            environment: 
                  POSTGRES_DB: ${DATABASE_NAME}
                  POSTGRES_USER: ${DATABASE_USER}
                  POSTGRES_PASSWORD: ${DATABASE_PASS}
            env_file:
             - .env
            healthcheck:
                  test: ["CMD-SHELL", "pg_isready -U $${DATABASE_USER} -d $${DATABASE_NAME}"]
                  interval: 10s
                  timeout: 5s
                  retries: 10